# Generated by Codex on 2026-05-11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContract",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=150, unique=True)),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("expiring", "Expiring"), ("expired", "Expired"), ("closed", "Closed")], default="active", max_length=30)),
                ("file", models.FileField(blank=True, null=True, upload_to="contracts/")),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["customer_name", "number"]},
        ),
        migrations.CreateModel(
            name="EquipmentUnit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("serial_number", models.CharField(max_length=150, unique=True)),
                ("inventory_number", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(choices=[("available", "Available"), ("reserved", "Reserved"), ("issued", "Issued"), ("customer", "At customer"), ("lab", "In lab"), ("written_off", "Written off"), ("needs_check", "Needs check")], default="available", max_length=30)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("responsible_person", models.CharField(blank=True, max_length=255)),
                ("reserved_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipment_units", to="catalog.customercontract")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="units", to="catalog.inventoryitem")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="equipment_units", to="locations.storagelocation")),
            ],
            options={"ordering": ["serial_number"]},
        ),
    ]
