# Generated by Codex on 2026-05-11

from django.db import migrations, models


def mark_equipment_as_serial(apps, schema_editor):
    InventoryItem = apps.get_model("catalog", "InventoryItem")
    InventoryItem.objects.filter(item_type="equipment").update(tracking_type="serial")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contract_equipmentunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="tracking_type",
            field=models.CharField(choices=[("quantity", "Quantity"), ("serial", "Serial numbers")], default="quantity", max_length=30),
        ),
        migrations.RunPython(mark_equipment_as_serial, migrations.RunPython.noop),
    ]
