# Generated by Django 6.0.3 on 2026-04-12 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('request_type', models.CharField(choices=[('repair_diagnostics', 'Ремонт / диагностика'), ('equipment_replacement', 'Замена оборудования'), ('internal_request', 'Внутренний запрос'), ('software_update', 'Обновление / запрос софта')], default='repair_diagnostics', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На проверке'), ('diagnostics', 'Диагностика'), ('awaiting_warehouse', 'Ожидает склад'), ('awaiting_procurement', 'Ожидает закупки'), ('reserved', 'Зарезервировано'), ('ready_to_ship', 'Готово к отгрузке'), ('shipped', 'Отгружено'), ('in_lab', 'В лаборатории'), ('received', 'Получено'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='new', max_length=50)),
                ('is_internal', models.BooleanField(default=False)),
                ('contract_exists', models.BooleanField(default=False)),
                ('recall_allowed', models.BooleanField(default=False)),
                ('customer_organization_id', models.UUIDField(blank=True, null=True)),
                ('integrator_organization_id', models.UUIDField(blank=True, null=True)),
                ('created_by_id', models.UUIDField()),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('current_assignee_id', models.UUIDField(blank=True, null=True)),
                ('requested_for_user_id', models.UUIDField(blank=True, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=255)),
                ('equipment_model', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('inventory_number', models.CharField(blank=True, max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='requests_app.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('author_username', models.CharField(blank=True, max_length=150)),
                ('author_role', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests_app.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('allow_analog', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests_app.servicerequest')),
            ],
        ),
    ]
