# Generated by Django 6.0.3 on 2026-04-10 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('request_type', models.CharField(choices=[('customer_request', 'Заявка заказчика'), ('internal_lab_loan', 'Временная выдача в лабораторию'), ('internal_equipment_request', 'Внутренний запрос оборудования'), ('repair_request', 'Ремонт / диагностика')], default='customer_request', max_length=50, verbose_name='Тип заявки')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новая'), ('in_review', 'На проверке'), ('awaiting_contract_check', 'Проверка контракта'), ('diagnostics', 'Диагностика'), ('awaiting_warehouse', 'Ожидает склад'), ('awaiting_procurement', 'Ожидает закупки'), ('reserved', 'Зарезервировано'), ('ready_to_ship', 'Готово к отгрузке'), ('shipped', 'Отгружено'), ('in_lab', 'В лаборатории'), ('received', 'Получено'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='new', max_length=50, verbose_name='Статус')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Внутренняя заявка')),
                ('contract_exists', models.BooleanField(default=False, verbose_name='Контракт подтвержден')),
                ('recall_allowed', models.BooleanField(default=False, verbose_name='Можно отозвать под внешний приоритет')),
                ('customer_organization_id', models.UUIDField(blank=True, null=True)),
                ('integrator_organization_id', models.UUIDField(blank=True, null=True)),
                ('created_by_id', models.UUIDField()),
                ('current_assignee_id', models.UUIDField(blank=True, null=True)),
                ('requested_for_user_id', models.UUIDField(blank=True, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=255, verbose_name='Оборудование')),
                ('equipment_model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=255, verbose_name='Инвентарный номер')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='Площадка / объект')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок возврата / завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('actor_role', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='requests_app.servicerequest')),
            ],
            options={
                'verbose_name': 'Событие заявки',
                'verbose_name_plural': 'События заявки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('author_role', models.CharField(max_length=50)),
                ('body', models.TextField(verbose_name='Текст комментария')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Внутренний комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests_app.servicerequest')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_item_id', models.UUIDField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('allow_analog', models.BooleanField(default=False, verbose_name='Разрешена замена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests_app.servicerequest')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
            },
        ),
    ]
