# Generated by Django 6.0.3 on 2026-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='current_assignee_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
