# Generated by Django 6.0.3 on 2026-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_servicerequest_allow_analog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_review', 'На согласовании'), ('diagnostics', 'Диагностика'), ('awaiting_warehouse', 'Ожидает склад'), ('awaiting_procurement', 'Ожидает закупки'), ('awaiting_return', 'Ожидает возврата'), ('awaiting_replacement', 'Ожидает замены'), ('awaiting_reallocation', 'Ожидает перераспределения'), ('partially_fulfilled', 'Частично исполнена'), ('shortage', 'Дефицит'), ('reserved', 'Зарезервировано'), ('ready_to_ship', 'Готово к отгрузке'), ('shipped', 'Отгружено'), ('awaiting_confirmation', 'Ожидает подтверждения'), ('in_lab', 'В лаборатории'), ('received', 'Получено'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='new', max_length=50),
        ),
    ]
