# Generated by Django 6.0.3 on 2026-05-08 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAnalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('analog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_for', to='catalog.inventoryitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='catalog.inventoryitem')),
            ],
            options={
                'unique_together': {('item', 'analog_item')},
            },
        ),
    ]
