# Generated by Django 6.0.3 on 2026-05-08 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('request_item_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('used', 'Used')], default='active', max_length=30)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='locations.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
