# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryreservation",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="reserved_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="contract_number",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="contract_file",
            field=models.FileField(blank=True, null=True, upload_to="inventory_contracts/"),
        ),
    ]
