# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contract_equipmentunit"),
        ("reservations", "0002_reservation_traceability"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryreservation",
            name="reservation_type",
            field=models.CharField(choices=[("quantity", "Quantity"), ("serial", "Serial numbers")], default="quantity", max_length=30),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="contract",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reservations", to="catalog.customercontract"),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="equipment_units",
            field=models.ManyToManyField(blank=True, related_name="reservations", to="catalog.equipmentunit"),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="status",
            field=models.CharField(choices=[("active", "Active"), ("released", "Released"), ("used", "Used"), ("expired", "Expired")], default="active", max_length=30),
        ),
    ]
