# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="responsible_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
