# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contract_equipmentunit"),
        ("transactions", "0002_transaction_responsibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="operation_kind",
            field=models.CharField(choices=[("supplier_receipt", "Supplier receipt"), ("warehouse_transfer", "Warehouse transfer"), ("customer_issue", "Customer issue"), ("lab_transfer", "Lab transfer"), ("customer_return", "Customer return"), ("lab_return", "Lab return"), ("write_off", "Write off"), ("stock_adjustment", "Stock adjustment")], default="supplier_receipt", max_length=40),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="contract",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="catalog.customercontract"),
        ),
        migrations.AddField(
            model_name="inventorytransactionitem",
            name="equipment_units",
            field=models.ManyToManyField(blank=True, related_name="transaction_items", to="catalog.equipmentunit"),
        ),
    ]
