# Generated by Django 6.0.3 on 2026-05-08 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('site', 'Site'), ('lab', 'Lab'), ('transit', 'Transit'), ('vehicle', 'Vehicle')], default='warehouse', max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization_id', 'name')},
            },
        ),
    ]
